version: '3.5'


services:
          application-backend:
            image: php:7.4.23-fpm-alpine3.13
            tty: true
            working_dir: /var/www/application/public
            volumes:
                  - .:/var/www/application/public/
            container_name: application-backend
